version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/myproject"
    schedule:
        interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
        